title: Tian.SQL
email: tiansql@gmail.com
#description:
#  Tian's site
url: "tiansql.github.io"
telegram_username:  tianwastaken
github_username:  tiansql
instagram_username:  typeoftian

kramdown:
  input: GFM
  hard_wrap: false
plugins:
  - jekyll-feed