title: Tian.SQL
email: playtoplayg@gmail.com
description: >-
  Tian's site
url: "tian-mc.github.io"
telegram_username:  tianwastaken
github_username:  Tian-MC
instagram_username:  typeoftian

kramdown:
  input: GFM
  hard_wrap: false