title: Tian.SQL
email: playtoplayg@gmail.com
description: >-
  Tian's site
url: "tian-mc.github.io"
telegram_username:  tianwastaken
github_username:  Tian-MC
weixin: weixin://dl/chat?colletticristian
discord: https://discordid.netlify.app/?id=1065712172283482142
lunar-link: https://discord.gg/eEdkHJxj


kramdown:
  input: GFM
  hard_wrap: false